var searchData=
[
  ['hardware_20apis_0',['Hardware APIs',['../group__hardware.html',1,'']]],
  ['hardware_5fadc_1',['hardware_adc',['../group__hardware__adc.html',1,'']]],
  ['hardware_5fbase_2',['hardware_base',['../group__hardware__base.html',1,'']]],
  ['hardware_5fboot_5flock_3',['hardware_boot_lock',['../group__hardware__boot__lock.html',1,'']]],
  ['hardware_5fclaim_4',['hardware_claim',['../group__hardware__claim.html',1,'']]],
  ['hardware_5fclocks_5',['hardware_clocks',['../group__hardware__clocks.html',1,'']]],
  ['hardware_5fdivider_6',['hardware_divider',['../group__hardware__divider.html',1,'']]],
  ['hardware_5fdma_7',['hardware_dma',['../group__hardware__dma.html',1,'']]],
  ['hardware_5fexception_8',['hardware_exception',['../group__hardware__exception.html',1,'']]],
  ['hardware_5fflash_9',['hardware_flash',['../group__hardware__flash.html',1,'']]],
  ['hardware_5fgpio_10',['hardware_gpio',['../group__hardware__gpio.html',1,'']]],
  ['hardware_5fi2c_11',['hardware_i2c',['../group__hardware__i2c.html',1,'']]],
  ['hardware_5finterp_12',['hardware_interp',['../group__hardware__interp.html',1,'']]],
  ['hardware_5firq_13',['hardware_irq',['../group__hardware__irq.html',1,'']]],
  ['hardware_5fpio_14',['hardware_pio',['../group__hardware__pio.html',1,'']]],
  ['hardware_5fpll_15',['hardware_pll',['../group__hardware__pll.html',1,'']]],
  ['hardware_5fpwm_16',['hardware_pwm',['../group__hardware__pwm.html',1,'']]],
  ['hardware_5fresets_17',['hardware_resets',['../group__hardware__resets.html',1,'']]],
  ['hardware_5frosc_18',['hardware_rosc',['../group__hardware__rosc.html',1,'']]],
  ['hardware_5frtc_19',['hardware_rtc',['../group__hardware__rtc.html',1,'']]],
  ['hardware_5fspi_20',['hardware_spi',['../group__hardware__spi.html',1,'']]],
  ['hardware_5fsync_21',['hardware_sync',['../group__hardware__sync.html',1,'']]],
  ['hardware_5fticks_22',['hardware_ticks',['../group__hardware__ticks.html',1,'']]],
  ['hardware_5ftimer_23',['hardware_timer',['../group__hardware__timer.html',1,'']]],
  ['hardware_5fuart_24',['hardware_uart',['../group__hardware__uart.html',1,'']]],
  ['hardware_5fvreg_25',['hardware_vreg',['../group__hardware__vreg.html',1,'']]],
  ['hardware_5fwatchdog_26',['hardware_watchdog',['../group__hardware__watchdog.html',1,'']]],
  ['hardware_5fxip_5fcache_27',['hardware_xip_cache',['../group__hardware__xip__cache.html',1,'']]],
  ['hardware_5fxosc_28',['hardware_xosc',['../group__hardware__xosc.html',1,'']]],
  ['headers_29',['External API Headers',['../group__misc.html',1,'']]],
  ['high_20level_20apis_30',['High Level APIs',['../group__high__level.html',1,'']]]
];
