var topics =
[
    [ "Hardware APIs", "group__hardware.html", "group__hardware" ],
    [ "boot_picobin_headers", "group__boot__picobin__headers.html", null ],
    [ "boot_picoboot_headers", "group__boot__picoboot__headers.html", null ],
    [ "boot_uf2_headers", "group__boot__uf2__headers.html", null ],
    [ "pico_base", "group__pico__base.html", "group__pico__base" ],
    [ "pico_usb_reset_interface_headers", "group__pico__usb__reset__interface__headers.html", null ],
    [ "pico_bit_ops", "group__pico__bit__ops.html", "group__pico__bit__ops" ],
    [ "pico_binary_info", "group__pico__binary__info.html", "group__pico__binary__info" ],
    [ "pico_divider", "group__pico__divider.html", "group__pico__divider" ],
    [ "pico_sync", "group__pico__sync.html", "group__pico__sync" ],
    [ "pico_time", "group__pico__time.html", "group__pico__time" ],
    [ "pico_util", "group__pico__util.html", "group__pico__util" ],
    [ "pico_stdlib", "group__pico__stdlib.html", "group__pico__stdlib" ],
    [ "pico_platform", "group__pico__platform.html", "group__pico__platform" ],
    [ "boot_stage2", "group__boot__stage2.html", null ],
    [ "pico_aon_timer", "group__pico__aon__timer.html", "group__pico__aon__timer" ],
    [ "pico_bootrom", "group__pico__bootrom.html", "group__pico__bootrom" ],
    [ "pico_bootsel_via_double_reset", "group__pico__bootsel__via__double__reset.html", null ],
    [ "pico_unique_id", "group__pico__unique__id.html", "group__pico__unique__id" ],
    [ "pico_atomic", "group__pico__atomic.html", null ],
    [ "pico_double", "group__pico__double.html", null ],
    [ "pico_int64_ops", "group__pico__int64__ops.html", null ],
    [ "pico_flash", "group__pico__flash.html", "group__pico__flash" ],
    [ "pico_float", "group__pico__float.html", null ],
    [ "pico_mem_ops", "group__pico__mem__ops.html", null ],
    [ "pico_malloc", "group__pico__malloc.html", null ],
    [ "pico_printf", "group__pico__printf.html", null ],
    [ "pico_rand", "group__pico__rand.html", "group__pico__rand" ],
    [ "tinyusb_device", "group__tinyusb__device.html", null ],
    [ "tinyusb_host", "group__tinyusb__host.html", null ],
    [ "pico_i2c_slave", "group__pico__i2c__slave.html", "group__pico__i2c__slave" ],
    [ "pico_async_context", "group__pico__async__context.html", "group__pico__async__context" ],
    [ "pico_btstack", "group__pico__btstack.html", "group__pico__btstack" ],
    [ "pico_cyw43_driver", "group__pico__cyw43__driver.html", "group__pico__cyw43__driver" ],
    [ "pico_lwip", "group__pico__lwip.html", "group__pico__lwip" ],
    [ "pico_cyw43_arch", "group__pico__cyw43__arch.html", "group__pico__cyw43__arch" ],
    [ "pico_crt0", "group__pico__crt0.html", null ],
    [ "pico_clib_interface", "group__pico__clib__interface.html", null ],
    [ "pico_cxx_options", "group__pico__cxx__options.html", null ],
    [ "pico_standard_binary_info", "group__pico__standard__binary__info.html", null ],
    [ "pico_standard_link", "group__pico__standard__link.html", null ],
    [ "pico_runtime_init", "group__pico__runtime__init.html", "group__pico__runtime__init" ],
    [ "pico_runtime", "group__pico__runtime.html", "group__pico__runtime" ],
    [ "pico_stdio", "group__pico__stdio.html", "group__pico__stdio" ],
    [ "pico_multicore", "group__pico__multicore.html", "group__pico__multicore" ]
];